package infrastructure

import (
	"net/http"

	todov1 "github.com/Ikedatomohiro/grpc-practice/todo/v1"        // generated by protoc-gen-go
	"github.com/Ikedatomohiro/grpc-practice/todo/v1/todov1connect" // generated by protoc-gen-connect-go
)

func NewTodoServiceHandler() http.Handler {
	todoer := &todov1.TodoServer{}
	mux := http.NewServeMux()
	path, handler := todov1connect.NewTodoServiceHandler(todoer)
	mux.Handle(path, handler)

	return mux
}
